HoneymoonShop/src/HoneymoonShop/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace HoneymoonShop.Controllers
{
    public class AdminController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        
    }
}

HoneymoonShop/src/HoneymoonShop/Controllers/CatalogusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HoneymoonShop.Data;
using Microsoft.EntityFrameworkCore;
using Models;
using HoneymoonShop.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HoneymoonShop.Controllers
{
    public class CatalogusController : Controller
    {
        ApplicationDbContext _context;

        public CatalogusController(ApplicationDbContext context)
        {
            _context = context;
        }
       


        public IActionResult Index()
        {

            try
            {
                ViewData["CategorieID"] = new SelectList(_context.Categorien, "CategorieID", "CategorieNaam");

                CatalogusFilterModel filterModel = new CatalogusFilterModel();

                filterModel.alleMerken = _context.Merken.ToList();
                filterModel.alleStijlen = _context.Stijlen.ToList();
                filterModel.alleNeklijnen = _context.Neklijnen.ToList();
                filterModel.alleSilhouetten = _context.Silhouetten.ToList();
                filterModel.alleKleuren = _context.Kleuren.ToList();
                filterModel.filteredJurken = _context.Jurken.ToList();
                var jurken = from j in _context.Jurken.Include(j => j.Categorie).Include(j => j.JurkKleuren).Include(j => j.Merk).Include(j => j.Neklijn).Include(j => j.Silhouette).Include(j => j.Stijl)
                             select j;
                foreach (var jurk in jurken)
                {
                    foreach (var jurkkleur in jurk.JurkKleuren)
                    {
                        jurkkleur.Jurk = _context.Jurken.Include(j => j.Categorie).Include(j => j.JurkKleuren).Include(j => j.Merk).Include(j => j.Neklijn).Include(j => j.Silhouette).Include(j => j.Stijl)
                                                .SingleOrDefault(m => m.JurkID == jurkkleur.JurkID);
                        jurkkleur.Kleur = _context.Kleuren.Include(j => j.JurkKleuren).SingleOrDefault(m => m.KleurID == jurkkleur.KleurID);
                    }
                }
                jurken = jurken.Where(j => j.Categorie.CategorieNaam == "Nieuwe Collectie");
                List<Jurk> list = new List<Jurk>();
                int count = 0;
                foreach (var item in jurken)
                {
                    if (count < 6)
                    {
                        list.Add(item);
                    }
                    count++;
                }
                filterModel.filteredJurken = list;
                return View(filterModel);
            } catch (Exception e)
            {
                return Json(e);
            }
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            else
            {
                var jurk = await _context.Jurken.Include(j => j.Categorie).Include(j => j.JurkKleuren).Include(j => j.Merk).Include(j => j.Neklijn).Include(j => j.Silhouette).Include(j => j.Stijl)
                    .SingleOrDefaultAsync(m => m.JurkID == id);
                
                foreach (var jurkkleur in jurk.JurkKleuren)
                {
                    jurkkleur.Jurk = _context.Jurken.Include(j => j.Categorie).Include(j => j.JurkKleuren).Include(j => j.Merk).Include(j => j.Neklijn).Include(j => j.Silhouette).Include(j => j.Stijl)
                                            .SingleOrDefault(m => m.JurkID == id);
                    jurkkleur.Kleur = _context.Kleuren.Include(j => j.JurkKleuren).SingleOrDefault(m => m.KleurID == jurkkleur.KleurID);
                }
                
                var jurken = from j in _context.Jurken.Include(j => j.Categorie).Include(j => j.JurkKleuren).Include(j => j.Merk).Include(j => j.Neklijn).Include(j => j.Silhouette).Include(j => j.Stijl)
                             select j;
                ViewData["Jurken"] = jurken;
                if (jurk == null)
                {
                    return NotFound();
                }

                jurk.Reviews = _context.Reviews.Where(r => r.JurkID == id).ToList();

                return View(jurk);
            }
        }
    

        public async Task<IActionResult> Collection(String id)
            //id = collection name
        {
            ViewData["CategorieID"] = new SelectList(_context.Categorien, "CategorieID", "CategorieNaam");

            CatalogusFilterModel filterModel = new CatalogusFilterModel();          

            filterModel.alleMerken = _context.Merken.ToList();
            filterModel.alleStijlen = _context.Stijlen.ToList();
            filterModel.alleNeklijnen = _context.Neklijnen.ToList();
            filterModel.alleSilhouetten = _context.Silhouetten.ToList();
            filterModel.alleKleuren = _context.Kleuren.ToList();
            filterModel.filteredJurken = _context.Jurken.ToList();


            var jurken = from j in _context.Jurken.Include(j => j.Categorie).Include(j => j.JurkKleuren).Include(j => j.Merk).Include(j => j.Neklijn).Include(j => j.Silhouette).Include(j => j.Stijl)
                         select j;
            if (string.IsNullOrEmpty(id))
            {
                filterModel.Categorie = "";
                return View(filterModel);
            }
            id = Uri.UnescapeDataString(id);
            jurken = jurken.Where(j => j.Categorie.CategorieNaam == id);
            if (jurken == null)
            {
                return NotFound();
            }
            filterModel.filteredJurken = await jurken.ToListAsync();
            filterModel.Categorie = id;
            return View(filterModel);
        }

        [HttpPost]
        public async Task<IActionResult> Collection(CatalogusFilterModel filterModel)
        {
            ViewData["CategorieID"] = new SelectList(_context.Categorien, "CategorieID", "CategorieNaam");

            //CREATE LISTS OF SELECTED INPUT
            var selectedMerkIDs = (from merk in filterModel.alleMerken
                                   where merk.Status == "checked"
                                   select merk.MerkID).ToList();
            //Pass user input to view model
            filterModel.selectedMerken = selectedMerkIDs;

            var selectedStijlIDs = (from stijl in filterModel.alleStijlen
                                    where stijl.Status == "checked"
                                    select stijl.StijlID).ToList();
            //Pass user input to view model
            filterModel.selectedStijlen = selectedStijlIDs;

            var selectedNeklijnIDs = (from neklijn in filterModel.alleNeklijnen
                                      where neklijn.Status == "checked"
                                      select neklijn.NeklijnID).ToList();
            //Pass user input to view model
            filterModel.selectedNeklijnen = selectedNeklijnIDs;

            var selectedSilhouetteIDs = (from silhouette in filterModel.alleSilhouetten
                                         where silhouette.Status == "checked"
                                         select silhouette.SilhouetteID).ToList();


            //Pass user input to view model
            filterModel.selectedSilhouetten = selectedSilhouetteIDs;


            var selectedKleurIDs = (from kleur in filterModel.alleKleuren
                                    where kleur.Status == "checked"
                                    select kleur.KleurID).ToList();
            //Pass user input to view model
            filterModel.selectedKleuren = selectedKleurIDs;

            int minPrijs = 0;
            int maxPrijs = 10000;

            //Convert PrijsRange to minimum and maximum prijs
            if (!string.IsNullOrEmpty(filterModel.PrijsRange))
            {
                minPrijs = Int32.Parse(filterModel.PrijsRange.Split(',')[0]);
                maxPrijs = Int32.Parse(filterModel.PrijsRange.Split(',')[1]);
            }

            //FILTER INPUT            
            var filteredJurken = from jurk in _context.Jurken.Include(j => j.Merk).Include(j => j.Stijl).Include(j => j.Neklijn).Include(j => j.Silhouette).Include(j => j.JurkKleuren)
                                 where (selectedMerkIDs == null || selectedMerkIDs.Count == 0 || selectedMerkIDs.Contains(jurk.MerkID))
                                 && (selectedStijlIDs == null || selectedStijlIDs.Count == 0 || selectedStijlIDs.Contains(jurk.StijlID))
                                 && (selectedNeklijnIDs == null || selectedNeklijnIDs.Count == 0 || selectedNeklijnIDs.Contains(jurk.NeklijnID))
                                 && (selectedSilhouetteIDs == null || selectedSilhouetteIDs.Count == 0 || selectedSilhouetteIDs.Contains(jurk.SilhouetteID))
                                 //&& (selectedKleurIDs == null || selectedKleurIDs.Count == 0 || selectedKleurIDs.Contains(jurk.KleurID))
                                 && jurk.Prijs > minPrijs
                                 && jurk.Prijs < maxPrijs
                                 select jurk;

            //SORTEER
            if (filterModel.sorteerOptie != null)
            {
                string caseSwitch = filterModel.sorteerOptie;
                switch (caseSwitch)
                {
                    case "Prijs Hoog/Laag":
                        filteredJurken = filteredJurken.OrderByDescending(j => j.Prijs);
                        break;
                    case "Prijs Laag/Hoog":
                        filteredJurken = filteredJurken.OrderBy(j => j.Prijs);
                        break;
                    case "Merk A-Z":
                        filteredJurken = filteredJurken.OrderBy(j => j.Merk.MerkNaam);
                        break;
                    case "Merk Z-A":
                        filteredJurken = filteredJurken.OrderByDescending(j => j.Merk.MerkNaam);
                        break;
                    default:

HoneymoonShop/src/HoneymoonShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HoneymoonShopProject</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/bootstrap-slider.css" />
        <link rel="stylesheet" href="~/css/Style.css" />
        <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
        <link rel="stylesheet" src="//normalize-css.googlecode.com/svn/trunk/normalize.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css" href="~/css/jquery.fancybox.css" media="screen" />
        <link rel="stylesheet" type="text/css" href="~/css/jPages.css" media="screen" />
        <link rel="stylesheet" type="text/css" href="~/css/bootstrap-datepicker3.css" media="screen"/>

    </environment>
    <environment names="Staging,Production">
        @*<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />*@
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/bootstrap-slider.css" />
        <link rel="stylesheet" href="~/css/Style.css" />
        <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
        <link rel="stylesheet" href="~/css/style.css" src="//normalize-css.googlecode.com/svn/trunk/normalize.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css" href="~/css/jquery.fancybox.css" media="screen" />
        <link rel="stylesheet" type="text/css" href="~/css/jPages.css" media="screen" />
        <link rel="stylesheet" type="text/css" href="~/css/bootstrap-datepicker3.css" media="screen" />        

    </environment>
</head>
<body class="backgroundcolor">
    <style>
        .navbar-brand{
            font-size:15px;
            font-weight:800;
        }
        .btn-default{
            font-weight: bold;
        }
        </style>
    <div class="container">
        <div class="row">
            <nav class="navbar navbar-default navbar-top">

                <div class="container-fluid" style="margin-top: 5px; margin-bottom: 2px; margin-left: 10px;">
                    <div class="navbar-header arial-bold">
                        <a class="navbar-brand" href="#">Website</a>
                        <a class="navbar-brand" href="#" style="margin-left: -5px;">Webshop</a>

                        <a class="navbar-brand" asp-controller="Admin" asp-action="Index">Admin</a>
                        <a class="navbar-brand" asp-controller="Catalogus" asp-action="Collection" asp-route-id="">Dressfinder</a>
                    </div>
                    <div class="navbar-header navbar-right">

                        <p class="navbar-text" style="font-size: 15px;"><b>T</b> (010) 4126143</p>
                        <p class="navbar-text"><span class="glyphicon glyphicon-search"></span></p>
                    </div>
                </div>
            </nav>
        </div>
    </div>
    <!--
    <div class="container">
        <div class="navbar navbar-custom">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
        </div>
    </div>s
    -->
    <div class="container">
        <div class="row">
            <header>
                <div class="navbar-collapse collapse navbarbackground">
                    <ul class="nav navbar-nav navbar-left">
                        <li><h1>Honeymoon shop</h1></li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right navbar-pink arial-bold" style="letter-spacing: 1px; margin-right: 8px;">
                        <li><a href="~/Home/Index">Home</a></li>
                        <li><a href="~/Bruid">Bruid</a></li>
                        <li><a href="~/Bruidegom">Bruidegom</a></li>
                        <li><a href="~/DeWinkel">DeWinkel</a></li>
                        <li><a href="#">Blog</a></li>
                        <li><a href="#">Contact</a></li>
                        <li><a asp-controller="afspraak" asp-action="datum" class="btn btn-default specialbutton" style="margin-top: 0px; padding: 10px; padding-top: 5px; padding-bottom: 5px; color: white; letter-spacing:1px; font-weight: bolder;">AFSPRAAK MAKEN</a></li>
                    </ul>
                </div>
                <!--
            <div class="intro-text">
                <div class="intro-lead-in">Welcome To Our Studio!</div>
                <div class="intro-heading">It's Nice To Meet You</div>
                <a href="#services" class="page-scroll btn btn-xl">Tell Me More</a>
            </div>
            -->

            </header>
        </div>
    </div>
    @RenderBody()

    <footer>
        <div class="container footer">
            <!--Top row-->
            <div class="row">

                <div class="col-md-4 footerimages footerleft">
                    <center>
                        <img class="img-responsive" src="~/images/T1.png" />
                    </center>
                </div>
                <div class="col-md-4 footerimages">
                    <center>
                        <img class="img-responsive" src="~/images/T2.png" />
                    </center>
                </div>
                <div class="col-md-4 footerimages footerright">
                    <center>
                        <img class="img-responsive" src="~/images/T3.png" />
                    </center>
                </div>


            </div>
            <!--Midden row-->
            <div class="row">

                <div class="col-md-12 midrow">
                    <div class="sans-serif-thin">Korte Hoogstraat 4, 3011GL Rotterdam  <b>email</b> info@honeymoonshop.nl <b>tel</b>(010) 412 61 43 <b>whatsapp</b>(06) 25 19 99 27</div>
                    <div class="sans-serif-thin"><strong>Openingstijden MA</strong> 12.00 - 17.30 <b>DI t/m VR</b> 09.30 - 17.30 <b>ZA</b> 09.30 - 17.30 <b>ZO</b> 11.00 - 17.00</div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4"></div>
                <div class="col-md-4 midcol">
                    <img class="img-responsive" src="~/images/indexa.png" alt="logo grand wedding show" />
                    <img class="img-responsive" src="~/images/brand.gif" alt="logo cbw" />
                </div>
                <div class="col-md-4"></div>
            </div>



            <!--Bottom row-->
            <div class="row foot">
                <div class="col-md-4">
                    <div class="footerlefttext">
                        <p class="style_p_h3">Winkel</p>
                        <ul class="sans-serif-thin">
                            <li><a>Over de Honeymoon shop</a></li>
                            <li><a>Servicepunten</a></li>
                            <li><a>Routebeschrijving</a></li>
                            <li><a>Beurzen en evenementen</a></li>
                            <li><a>Vacatures</a></li>
                            <li><a>Verkoopvoorwaarden</a></li>
                            <li><a>CBW erkend</a></li>
                            <li><a>Contact</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-4">
                    <p class="style_p_h3">Service</p>
                    <ul class="sans-serif-thin">
                        <li><a>Beoordeling</a></li>
                        <li><a>Dressfinder</a></li>
                        <li><a>Gratis trouwmagazine</a></li>
                        <li><a>Nieuwsbrief</a></li>
                        <li><a>Vell gestelde vragen</a></li>
                        <li><a>CWB erkend</a></li>
                        <li><a>Reinigen van je trouwjurk</a></li>
                        <li><a>10 reden om je afspraak te maken</a></li>
                        <li><a>The Perfect Match</a></li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <div class="footerrighttext">
                        <p class="style_p_h3">Acties</p>
                        <ul class="sans-serif-thin">
                            <li><a>The Grand Wedding Show</a></li>
                            <li><a>Summer Sale</a></li>
                            <li><a>Trouwjurken onder de 1000 euro</a></li>
                            <li><a>Trouwjurken voor de volslanke bruid</a></li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>

    </footer>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script type="text/javascript" src="~/js/bootstrap-slider.js"></script>
        <script type="text/javascript" src="~/lib/jPages.js"></script>
        <script type="text/javascript" src="~/js/bootstrap-datepicker.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        @*<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>*@
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script type="text/javascript" src="~/js/bootstrap-slider.js"></script>
        <script type="text/javascript" src="~/lib/jPages.js"></script>
        <script type="text/javascript" src="~/js/bootstrap-datepicker.js"></script>        

        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)



    <script type="text/javascript">
        $(document).ready(function () {

            $('#ex12c').slider({
                id: "slider12c", min: 0, max: 10000, range: true, value: [1000, 9000],
                tooltip: 'always', tooltip_split: true, tooltip_position: 'bottom',
                formatter: function (value) {
                    return value;
                }
            });

            $('.datepicker').datepicker({
                language: "nl"
            });

            $(function () {
                $(".holder").jPages({
                    containerID: "itemContainer",
                    perPage: 12,
                    previous: "span.arrowPrev",
                    next: "span.arrowNext"
                });

                $(".itemsPerPageSelect").change(function () {
                    var newPerPage = parseInt($(this).val());

                    $(".holder").jPages("destroy").jPages({
                        containerID: "itemContainer",
                        perPage: newPerPage,
                        previous: "span.arrowPrev",
                        next: "span.arrowNext"
                    });
                });
            });
        });
    </script>
</body>
</html>

HoneymoonShop/src/HoneymoonShop/Views/Shared/_ReviewPartial.cshtml
@model Models.Jurk

<table class="table">
    <thead>
        <tr>            
            <th>
                Klant Naam 
            </th>
            <th>
                Klant Beoordeling
            </th>

            <th>
                Klant Review
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Reviews)
        {
            
            <tr>
                
                <td>
                    @Html.DisplayFor(modelItem => item.Naam)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Beoordeling)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.klantReview)
                </td>
                
            </tr>
        }
    </tbody>
    
</table>